namespaces:
  application: sales-test-ns
  gateway: sales-gateway-ns

services:
  auth:
    image: kubectlandchill/auth-service
    tag: v1.2.1
    port: 3000
    replicas: 2
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m" 
      memory: "512Mi"
    
  notifications:
    image: kubectlandchill/sales-notification-service
    tag: v1.0.1
    port: 3000
    replicas: 2
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m" 
      memory: "512Mi"


  customer:
    image: kubectlandchill/customer-service
    tag: v1.2.1
    port: 3000
    replicas: 2
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m" 
      memory: "512Mi"
    

  order:
    image: kubectlandchill/order-service
    tag: v1.2.1
    port: 3000
    replicas: 2
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m" 
      memory: "512Mi"

  invoice:
    image: kubectlandchill/invoice-service
    tag: v1.1.0
    port: 3000
    replicas: 2
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m" 
      memory: "512Mi"


  payment:
    image: kubectlandchill/payment-service
    tag: v1.1.0
    port: 3000
    replicas: 2
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m" 
      memory: "512Mi"


  sales-ui:
    image: kubectlandchill/sales-invoice-ui
    tag: v1.1.4
    port: 3000
    replicas: 2
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "250m" 
      memory: "720Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70

database:
  enabled: true
  image: mysql:8.4
  storage: 2Gi

gateway:
  enabled: true
  port: 80

routes:
  auth:
    path: /api/auth
    service: auth-service

  customers:
    path: /api/customers
    service: customer-service

  orders:
    path: /api/orders
    service: order-service

  invoices:
    path: /api/invoices
    service: invoice-service

  payments:
    path: /api/payments
    service: payment-service

  ui:
    path: /
    service: sales-ui-service