global:
  environment: dev
  imagePullPolicy: IfNotPresent

namespaces:
  application: sales-test-ns
  gateway: sales-gateway-ns

# ---------------- SERVICES ----------------

auth:
  name: auth-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/auth-service
    tag: v1.2.1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

customer:
  name: customers-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/customer-service
    tag: v1.2.1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

order:
  name: order-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/order-service
    tag: v1.2.1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

invoice:
  name: invoice-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/invoice-service
    tag: v1.1.0
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

payment:
  name: payment-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/payment-service
    tag: v1.1.0
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

notifications:
  name: notification-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-notification-service
    tag: v1.0.1

salesUi:
  name: sales-ui-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-invoice-ui
    tag: v1.1.4
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "720Mi"

# ---------------- HPA ----------------

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70

# ---------------- DATABASE ----------------

database:
  enabled: true
  image:
    repository: mysql
    tag: "8.4"
  storage:
    size: 2Gi

# ---------------- GATEWAY ----------------

gateway:
  enabled: true
  port: 80

# ---------------- ROUTES ----------------

routes:
  auth:
    path: /api/v1/auth
    service: auth-service

  customers:
    path: /api/v1/customers
    service: customer-service

  orders:
    path: /api/v1/orders
    service: order-service

  invoices:
    path: /api/v1/invoices
    service: invoice-service

  payments:
    path: /api/v1/payments
    service: payment-service

  ui:
    path: /
    service: sales-ui-service