apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.order.name }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: order
spec:
  type: ClusterIP
  selector:
    app: order-microservice
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP